# general
colorscheme gruvbox-dark

set-option global grepcmd 'rg --column'
set-option global autoreload yes
set-option global ui_options 'gui_set_font=Ubuntu Mono 12'

set-face global CurSearch +u
hook global RegisterModified '/' %{ add-highlighter -override global/search regex "%reg{/}" 0:CurSearch }

add-highlighter global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+rb

add-highlighter global/ show-matching
hook global BufCreate .* %[
    add-highlighter buffer/ number-lines -relative -hlcursor
    add-highlighter buffer/ wrap
]

git-update-diff-on-write

# statusline
set-option global modelinefmt '%val{bufname} {comment}%sh{ [ -n "$kak_opt_filetype" ] && printf "($kak_opt_filetype) "}%val{cursor_line}:%val{cursor_char_column} {default}{{context_info}} {{mode_info}} - %val{client}@[%val{session}]'

# enable editorconfig
hook global BufOpenFile .* %{ editorconfig-load }
hook global BufNewFile .* %{ editorconfig-load }

# switch cursor color in insert mode
set-face global InsertCursor black,blue

hook global ModeChange .*:.*:insert %{
    set-face window PrimaryCursor InsertCursor
    set-face window PrimaryCursorEol InsertCursor
}

hook global ModeChange .*:insert:.* %{ try %{
    unset-face window PrimaryCursor
    unset-face window PrimaryCursorEol
}}

# mappings
map global insert <c-w> '<esc>bdi'

map global normal '#' ':comment-line<ret>'
map global normal <esc> ':set-register slash ""<ret>'

map global user -docstring 'delete buffer' x ':delete-buffer<ret>'
map global user -docstring 'find file' f ':find '
map global user -docstring 'grep' g ':grep '

map -docstring "xml tag objet" global object t %{c<lt>([\w.]+)\b[^>]*?(?<lt>!/)>,<lt>/([\w.]+)\b[^>]*?(?<lt>!/)><ret>}

hook global -always BufOpenFifo '\*grep\*' %{
    map global normal <minus> ':grep-next-match<ret>'
    map global normal <a-minus> ':grep-previous-match<ret>'
}

hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }

hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}

# functions
define-command ide %{
    rename-client main
    set-option global jumpclient main

    set-option global toolsclient clippy
    set-option global docsclient clippy
    new %{ rename-client clippy; files }
}

# aliases
alias global s insert-snippet

alias global p ghq-cd
alias global pnew ghq-create
alias global pget ghq-get-and-cd

alias global files files-new-or-focus

# format
hook global BufSetOption filetype=(c|cpp) %{
    set-option buffer formatcmd 'clang-format'
}

hook global BufSetOption filetype=(javascript|typescript|json) %{
    set-option buffer formatcmd "prettier --stdin-filepath=%val{buffile}"
}

hook global BufSetOption filetype=python %{
    set-option buffer formatcmd "black -"
}

# source other config files
source "%val{config}/kakqt.kak"
try %{
    require-module kakouneqt
}

# source plugins
source "%val{config}/plugins.kak"

# Source a local project kak config if it exists
define-command config -docstring "open local config" %{ edit .local.kak }
try %{ source .local.kak }
